package testsocket.model;

public enum SeverRespone {
	SEVER_MESSAGE,
	USER_MESSAGE,
	USER_LOGIN,
	USER_LOGOUT,
	USER_SEARCH_FRIEND_RESOULT,
	USER_PROMISE_ADD_FRIEND,
	USER_ADD_FRIEND,
	USER_FILE,
	REGISTER_SUCCESS,
	REGISTER_FAILURE,
	USER_GROUP_MESSAGE,
	USER_SEARCH_GROUP_RESOULT,
	USER_NOT_ONLINE,
	USER_REFRESH,
}
